[versions]
hikariCP = "6.2.1"
invApiVer = "4.1.10"
gson = "2.11.0"
libly = "2.0.0-SNAPSHOT"
reflections = "0.10.2"
paperLib = "1.0.7"
caffeine = "3.1.8"
paper = "1.21-R0.1-SNAPSHOT"
vault = "1.7.1"
placeholderApi = "2.11.6"
bungeecord = "1.21-R0.1-SNAPSHOT"
jedis = "5.2.0"
adventure = "4.17.0"
adventurePlatform = "4.3.4"
velocity = "3.1.1"
guice = "7.0.0"
configurate = "4.2.0-YAML-COMMENTED-SNAPSHOT"
scoreboard = "2.0.1"
shadowJar = "8.3.5"
pluginYml = "0.6.0"
guava = "33.3.1-jre"
apacheCommons = "3.14.0"
ebean = "15.1.0"
flyway = "10.12.0"
protoc = "4.29.1"
super-vanish = "6.2.18-3"
inventory = "1.0.0-ee06bf8"
mock-bukkit = "3.9.0"
brigadier = "1.0.18"
commodore = "2.2"
google-auto-value = "1.11.0"
google-auto-service = "1.1.1"
luckperms = "5.4"
neznamy-tab-api = "5.0.4"

[libraries]
hikariCP = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikariCP" }
invCore = { group = "com.github.hamza-cskn.obliviate-invs", name = "core", version.ref = "invApiVer" }
invAdvancedSlots = { group = "com.github.hamza-cskn.obliviate-invs", name = "advancedslot", version.ref = "invApiVer" }
invPagination = { group = "com.github.hamza-cskn.obliviate-invs", name = "pagination", version.ref = "invApiVer" }
configurableGui = { group = "com.github.hamza-cskn.obliviate-invs", name = "configurablegui", version.ref = "invApiVer" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
liblyBukkit = { group = "com.alessiodp.libby", name = "libby-bukkit", version.ref = "libly" }
liblyBungee = { group = "com.alessiodp.libby", name = "libby-bungee", version.ref = "libly" }
libbyVelocity = { group = "com.alessiodp.libby", name = "libby-velocity", version.ref = "libly" }
libbyPaper = { group = "com.alessiodp.libby", name = "libby-paper", version.ref = "libly" }
reflections = { group = "org.reflections", name = "reflections", version.ref = "reflections" }
paperLib = { group = "io.papermc", name = "paperlib", version.ref = "paperLib" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
vault = { group = "com.github.MilkBowl", name = "VaultAPI", version.ref = "vault" }
placeholderApi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderApi" }
bungeecord = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungeecord" }
jedis = { group = "redis.clients", name = "jedis", version.ref = "jedis" }
miniMessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureBukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventurePlatform" }
adventureBungee = { group = "net.kyori", name = "adventure-platform-bungeecord", version.ref = "adventurePlatform" }
textPlainSerializer = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
textLegacySerializer = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
google-guice-assistedinject = { group = "com.google.inject.extensions", name = "guice-assistedinject", version.ref = "guice" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
configurateGson = { group = "org.spongepowered", name = "configurate-gson", version.ref = "configurate" }
configurateHocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
configurateYaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }
apacheCommons = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommons" }
jarRelocator = { group = "me.lucko", name = "jar-relocator", version = "1.7" }
# Scoreboard stuff
scoreboard = { group = "com.github.megavexnetwork.scoreboard-library", name = "scoreboard-library-api", version.ref = "scoreboard" }
scoreboard-implementation = { group = "com.github.megavexnetwork.scoreboard-library", name = "scoreboard-library-implementation", version.ref = "scoreboard" }
# Scoreboard packets adapter
scoreboard-modern = { group = "com.github.megavexnetwork.scoreboard-library", name = "scoreboard-library-modern", version.ref = "scoreboard" }
scoreboard-packetevents = { group = "com.github.megavexnetwork.scoreboard-library", name = "scoreboard-library-packetevents", version.ref = "scoreboard" }
scoreboard-8 = { group = "com.github.megavexnetwork.scoreboard-library", name = "scoreboard-library-v1_8_R3", version.ref = "scoreboard" }
# Auto service
auto-service = "com.google.auto.service:auto-service:1.0.1"
auto-service-annotations = "com.google.auto.service:auto-service-annotations:1.0.1"
google-auto-value-processor = { module = "com.google.auto.value:auto-value", version.ref = "google-auto-value" }
google-auto-value-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "google-auto-value" }
ebean = { group = "io.ebean", name = "ebean", version.ref = "ebean" }
ebean-ddl-generator = { group = "io.ebean", name = "ebean-ddl-generator", version.ref = "ebean" }
ebean-migration = { group = "io.ebean", name = "ebean-migration", version = "14.0.0" }
protocol-buffers-lite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protoc" }
superVanish = { group = "com.github.LeonMangler", name = "SuperVanish", version.ref = "super-vanish" }
nookure-core-inventory = { group = "com.nookure.core", name = "NookCore-Inventory", version.ref = "inventory" }
mockBukkit = { group = "com.github.seeseemelk", name = "MockBukkit-v1.20", version.ref = "mock-bukkit" }
mojang-brigadier = { group = "com.mojang", name = "brigadier", version.ref = "brigadier" }
lucko-commodore = { group = "me.lucko", name = "commodore", version.ref = "commodore" }
lucko-luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }
neznamy-tab-api = { group = "com.github.NEZNAMY", name = "TAB-API", version.ref = "neznamy-tab-api" }

[bundles]
invAPI = ["invCore", "invAdvancedSlots", "invPagination", "configurableGui"]
scoreboard = ["scoreboard", "scoreboard-implementation", "scoreboard-modern", "scoreboard-packetevents", "scoreboard-8"]

[plugins]
shadowJar = { id = "com.gradleup.shadow", version.ref = "shadowJar" }
pluginYmlBukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginYml" }
pluginYmlBungee = { id = "net.minecrell.plugin-yml.bungee", version.ref = "pluginYml" }
pluginYmlPaper = { id = "net.minecrell.plugin-yml.paper", version.ref = "pluginYml" }
grgit = { id = "org.ajoberstar.grgit", version = "5.2.1" }
grgitPublish = { id = "org.ajoberstar.git-publish", version = "4.2.1" }
ebean = { id = "io.ebean", version.ref = "ebean" }
libby = { id = "xyz.kyngs.libby.plugin", version = "1.0.0" }
runPaper = { id = "xyz.jpenilla.run-paper", version = "2.3.0" }
testLogger = { id = "com.adarshr.test-logger", version = "4.0.0"}
minotaur = { id = "com.modrinth.minotaur", version = "2.+" }